{% set name = "kombu" %}
{% set version = "4.4.0" %}
{% set sha256 = "750579c10e4ce82636cebdaad3cfc96970b4c7c483a040bb94fb52040bc53a48" %}
{% set build = 0 %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    noarch: python
    number: {{ build }}
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - pip

    run:
        - python
        - simplejson
        - sqlalchemy
        - amqp >=2.1.4,<3.0

test:
    imports:
        - kombu
        - kombu.asynchronous
        - kombu.asynchronous.aws
        - kombu.asynchronous.http
        - kombu.transport
        - kombu.transport.sqlalchemy
        - kombu.transport.virtual
        - kombu.utils

about:
    home: https://kombu.readthedocs.org
    license_file: LICENSE
    license: BSD 3-Clause
    summary: 'Messaging library for Python'
    dev_url: https://github.com/celery/kombu
    doc_url: https://kombu.readthedocs.org

extra:
    recipe-maintainers:
        - anguslees
        - kwilcox
        - pmlandwehr
