{% set name = "kombu" %}
{% set version = "3.0.35" %}
{% set md5 = "6483ac8ba7109ec606f5cb9bd084b6ef" %}
{% set build = 0 %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    md5: {{ md5 }}

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
        - anyjson >=0.3.3
        - amqp >=1.4.9,<2.0
    run:
        - python
        - anyjson >=0.3.3
        - amqp >=1.4.9,<2.0

test:
    imports:
        - kombu
        - kombu.async
        - kombu.tests
        - kombu.tests.async
        - kombu.tests.transport
        - kombu.tests.transport.virtual
        - kombu.tests.utils
        - kombu.transport
        - kombu.transport.virtual
        - kombu.utils
    requires:
        - mock >=0.7.0
        - nose
        - setuptools >=0.7

about:
    home: http://kombu.readthedocs.org
    license: BSD License
    summary: Messaging library for Python

extra:
    recipe-maintainers:
        - kwilcox
