{% set name = "kombu" %}
{% set version = "5.5.4" %}
{% set u_tests_to_skip = "--ignore=gh_src/t/unit/transport/test_azurestoragequeues.py " %}
{% set u_tests_to_skip = u_tests_to_skip + "--ignore=gh_src/t/unit/transport/test_gcpubsub.py " %}
{% set u_tests_to_skip = u_tests_to_skip + "--ignore=gh_src/t/unit/transport/test_gcpubsub.py " %}
{% set i_tests_to_skip = "--ignore=gh_src/t/integration/test_redis.py " %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 886600168275ebeada93b888e831352fe578168342f0d1d5833d88ba0d847363
  - url: https://github.com/celery/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 7793a288cc0316d06e66785a18182b8629a692a9fb2976b85c51cb466f95c008
    folder: gh_src

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - amqp >=5.1.1,<6.0.0
    - vine 5.1.0
    - backports.zoneinfo >=0.2.1  # [py<39]
    - python-tzdata >=2025.2  # [py>=39]
    - packaging

test:
  imports:
    - kombu
    - kombu.asynchronous
    - kombu.asynchronous.aws
    - kombu.asynchronous.http
    - kombu.transport
    - kombu.transport.virtual
    - kombu.utils
  source_files:
    - gh_src
  requires:
    - hypothesis
    - botocore
    - pytest
    - google-api-core
    - pip
  commands:
    - pip check
    - pytest -vv gh_src/t/unit {{ u_tests_to_skip }} -k "not test_driver_version"
    - pytest -vv gh_src/t/integration {{ i_tests_to_skip }}

about:
  home: https://kombu.readthedocs.org
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Messaging library for Python
  description: |
    Kombu is a messaging library for Python.
    The aim of Kombu is to make messaging in Python as easy as possible by providing an idiomatic high-level interface for the AMQ protocol, and also provide proven and tested solutions to common messaging problems.
    AMQP is the Advanced Message Queuing Protocol, an open standard protocol for message orientation, queuing, routing, reliability and security, for which the RabbitMQ messaging server is the most popular implementation.
  dev_url: https://github.com/celery/kombu
  doc_url: https://docs.celeryq.dev/projects/kombu

extra:
  recipe-maintainers:
    - anguslees
    - kwilcox
    - pmlandwehr
    - igortg
