travis:
  secure:
    BINSTAR_TOKEN: U5lXxUQcxwSE0TrHDJdfF5OPCER2EfQnIHSNLkZNxGT79M0+NqaSQgJH7vYFv9Lp8pIPmtHKljtghAoJ72dejAPO9ICYxWBnNDK2zoha2EH0LGTG51FlrCe5Gf5r4+WFLFlxRG4sYkB5/XoEZzKGkHUu3ZR5EM1sQcTeeAiBb/AePico7r0qN7canZqzWzPoPjGMZi0t+2hSanmRz93A6s+PbcB6WK7wVVqzH9VAwkFjwM0s3oxBSS4qgX+s+cSM4ayHjkw7oRSXY4rqB+xl4qzJeCtOqgYu2mrdduF8cSokktenV8CIF2HcErCc+dRb+eIjmg7IJmF+Fm++0mVcUrYkDOsKlwBijjNJchFEReIkihQa9liTKCsb+y6Vc2l8agTzaWbwbCLFeMDcKwayleGrrZSLDACLMDVf1ghHDU/fQIZOPDfYlI81jKyu0qeVct0m9uh+UaiwgOkrPUkOY4FdxuQKXHxIRAnM1cNgGrrkUHOBn46BcZzoCpSz/c8hYAAet7Gwv/FpVt99ZjqfC19gXTVQYGDlPsvZwo3yHw+iTZHTWm9I02fCUjmTegRIz4CVD4seDVWDSNuwyFN0YUZo8tSEHJMDnYauuWprUSxpkxGGQUxSl0nzy/XCYSA+Wbtk9qhrYEojfjXLyozXE80Zn8PZWuK1OWkiPXMArc4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
