travis:
  secure:
    BINSTAR_TOKEN: 1sDW/NsArSWZvz/p0tsgiudKnlAK9g2MOhjgUzfH54W34oXsoLO3jsC4MnWewN701Qv+o6y0k0/GEAR3tAc4SfM+Y2sViYY6zGg3vfvLvPA5cYpRmL3B1iCTQwIj5dKAwIKA1cXOt4XOxi+bIoUbX6hWhXKEy82oqf7Sywkg6tHPL54b60Ruibh1ZeqJczU7UmP3ft0b3qbfKjVvI9DXhj9JgtU3U/Hfnb5xlXOo1tPWdiAxYHamk1l6CVP/x8TcUArqJfjF2azn1hAfXJtxw5/hWDJkIkhOpOxI4TgK80wBIYIX6bX3nBjkJ8FeZ0IIonLigX4uraubdbGwUuPWvI0570fX4uGdnA6Vwsnox11IIjhETc37jpBCNVpUBYfh/zIhbHQsCIYblXxMWebd7biuwuX4DGVrDdWbkgFLZctenRPKJ9ElCxq75WZ4R+bHGYrs/gk/owHH1td8vjF++KOsHKwiY6Cy7mrwrxuwbClHQPqqOGp2dkGqhfyFTUqKl1oxXj6f8dbN1QKDu5wgjzjqcn2H23Ebo9bPpALmNuG8asKTO4w5gWNjFqKHkEeoXYM84xprwKmuWQ1STsUGeUGYQ9P7CV1j9VtQMDx+W161Mr2R1h/o7dkzaE27yQ8GjA9fV+DscRJHn9ZoNykKTVdkK4i3VTfPxUQ+TvpOYp8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
